# Task 1
Write down a python program which takes two strings as input and calculate the
Levenshtein/Edit distance between the two strings.


In [ ]:
import numpy as np

In [ ]:
def levenshteinFormula(i,j,str1,str2,matrix):
  if (min(i,j)==0):
    return max(i,j)
  else:
    a = matrix[i-1][j]+1
    b = matrix[i][j-1]+1
    if (str1[i-1]!=str2[j-1]):
      c = matrix[i-1][j-1]+1
    else:
      c = matrix[i-1][j-1]
    return min(a,b,c)

In [ ]:
def levenshteinDistance(str1,str2):
  lenx = len(str1)+1
  leny = len(str2)+1
  matrix = np.zeros((lenx,leny))
  for x in range(lenx):
    matrix[x,0]=x
  for y in range(leny):
    matrix[0,y]=y
  for x in range(1,lenx):
    for y in range(1,leny):
      matrix[x][y]=levenshteinFormula(x,y,str1,str2,matrix)
  print(matrix)
  print(f"Total operations required to to change text is {matrix[lenx-1][leny-1]}")

  f = open("/home/DIP/result.txt", "w")
  f.write(f"Total operations required to change text is {matrix[lenx-1][leny-1]}")
  f.close()

In [ ]:
levenshteinDistance("kitten","sitting")

[[0. 1. 2. 3. 4. 5. 6. 7.]
 [1. 1. 2. 3. 4. 5. 6. 7.]
 [2. 2. 1. 2. 3. 4. 5. 6.]
 [3. 3. 2. 1. 2. 3. 4. 5.]
 [4. 4. 3. 2. 1. 2. 3. 4.]
 [5. 5. 4. 3. 2. 2. 3. 4.]
 [6. 6. 5. 4. 3. 3. 2. 3.]]
Total operations required to to change text is 3.0


# Task 2
Now modify the above written program in such a way that it takes two text files containing single- line and lowercase English sentences named as reference.txt and hypothesis.txt, and outputs the file result.txt containing Levenstein distance of these two files as below. The distance should be word level and not character level

In [ ]:
f = open("/home/DIP/hypothesis.txt", "r")
file1 = f.read()

In [ ]:
f = open("/home/DIP/reference.txt", "r")
file2 = f.read()

In [ ]:
file1_words = file1.split(" ")
file2_words = file2.split(" ")

In [ ]:
levenshteinDistance(file1_words,file2_words)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.
  17. 18. 19.]
 [ 2.  1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.
  16. 17. 18.]
 [ 3.  2.  1.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.
  16. 17. 18.]
 [ 4.  3.  2.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.
  15. 16. 17.]
 [ 5.  4.  3.  3.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.
  14. 15. 16.]
 [ 6.  5.  4.  4.  3.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.
  13. 14. 15.]
 [ 7.  6.  5.  5.  4.  3.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.
  12. 13. 14.]
 [ 8.  7.  6.  6.  5.  4.  3.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.
  11. 12. 13.]
 [ 9.  8.  7.  7.  6.  5.  4.  3.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9.
  10. 11. 12.]
 [10.  9.  8.  8.  7.  6.  5.  4.  3.  2.  2.  3.  4.  5.  6.  7.  8.  9.
  10. 11. 12.]
 [11. 10.  9.  9.  8.